owner: CustomIPTV
repo: RealTimeStatus

sites:
  - name: Servidor 1
    url: http://suptv.co
  - name: Servidor 2
    url: https://dash.centre6.co
    
assignees:
  - CustomIPTV

status-website:
  baseUrl: /RealTimeStatus
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Custom IPTV Status
  introTitle: "**Real-time server status**."
  introMessage: This page shows in real time the status of the servers.
